# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 258beae6e8fe771dd263413adf9039b2daea3ce24069a2fe26feb7cd6aa3ec0b8b8c8ba40df2566dd7a50ea0343ee5d0279a7230e523ce75f2af98b32dde1460

test:
  secret_key_base: 22a1c7c5ddbaf7f80532711fffd7addad78110e88c3dfbe83caff48921d17dc0e2786e9b8f6a279bb014d4e4b3d41aad5e6a5c021b82d008e13c7b46a10f672d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
